// Rewrites the APP_SHELL list in sw.js from the files on disk and sets the cache version
// from package.json. Run after adding files or bumping the version: npm run sw
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, sep } from 'node:path';

const DIRS = ['css', 'js', 'assets', 'data', 'vendor', 'partners'];
const ROOT_FILES = ['./', './index.html', './manifest.webmanifest'];

function listFiles(dir) {
  return readdirSync(dir)
    .sort()
    .flatMap((name) => {
      const full = join(dir, name);
      return statSync(full).isDirectory() ? listFiles(full) : [full.split(sep).join('/')];
    });
}

const files = DIRS.filter((dir) => existsSync(dir)).flatMap(listFiles);
const shell = [...ROOT_FILES, ...files.map((f) => `./${f}`)];
const { version } = JSON.parse(readFileSync('package.json', 'utf8'));

let sw = readFileSync('sw.js', 'utf8');
sw = sw.replace(/const CACHE_VERSION = '[^']*';/, `const CACHE_VERSION = 'aether-v${version}';`);
sw = sw.replace(/const APP_SHELL = \[[\s\S]*?\];/, `const APP_SHELL = [\n${shell.map((f) => `  '${f}',`).join('\n')}\n];`);
writeFileSync('sw.js', sw);

writeFileSync('js/version.js', `// Shown in Profiel. Generated by scripts/update-sw.js from package.json.\nexport const APP_VERSION = '${version}';\n`);
console.log(`sw.js: ${shell.length} files, version ${version}`);
